### ISSUE TITLE
openssh.config fails with "No such file or directory"

### ISSUE THREAD

**Issue by denschub** [saltstack-formulas/openssh-formula#103]
Just upgraded both the master and the minion to v2017.7.0. Now, when there is a mismatch of the config file, applying the config fails:

```
----------
          ID: sshd_config
    Function: file.managed
        Name: /etc/ssh/sshd_config
      Result: False
     Comment: Failed to commit change: [Errno 2] No such file or directory: /tmp/__salt.tmp._skAAZ
     Started: 23:55:26.828903
    Duration: 103.767 ms
     Changes:
              ----------
              diff:
                  Replace text file with binary file
```

It works fine when the config file matches the template, but if there are any changes, 💥.
