### ISSUE TITLE
Using openssh.config To Configure Just Keys Fails

### ISSUE THREAD

**Issue by tmeneau** [saltstack-formulas/openssh-formula#130]
Using the `openssh.config` state to configure just SSH keys (leaving the minion's sshd configuration untouched) results in the following error:

```
primarymaster:
    Data failed to compile:
----------
    Cannot extend ID 'sshd_config' in 'base:openssh.config'. It is not part of the high state.
This is likely due to a missing include statement or an incorrectly typed ID.
Ensure that a state with an ID of 'sshd_config' is available
in environment 'base' and to SLS 'openssh.config'
```

Example pillar (keys truncated for brevity, but otherwise complete):

```yaml
openssh:
  provide_rsa_keys: True
  rsa:
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKC...
      -----END RSA PRIVATE KEY-----
    public_key: |
      ssh-rsa AAAAB3...
```

This is because of [the require_in added to the key management states](https://github.com/saltstack-formulas/openssh-formula/blob/master/openssh/config.sls#L41) pointing to the sshd_config state, which [doesn't exist if there's no sshd_config pillar defined](https://github.com/saltstack-formulas/openssh-formula/blob/master/openssh/config.sls#L6). The use case here is admittedly a testing scenario where the distribution's default sshd config is fine, but I don't think that's too much of an edge case to support.
