### ISSUE TITLE
auth_map: cant create options

### ISSUE THREAD

**Issue by genaumann** [saltstack-formulas/openssh-formula#140]
Hello, I wanted to add some keys to my authorized_keys.

I need some options, like `from="8.8.8.8"` and `command="uptime"`. I tried to create this entries with the auth_map state of this formula.

### First problem

`pillar file`

```
openssh:
  ...
  auth_map:
    ssh_to_host:
      source: salt://ssh/keys
      users:
        user1:
          first-key:
            options:
              from=8.8.8.8
          second-key:
            options:
              command=uptime
...
```

**I get the following result:**

`f,r,o,m,=,8,.,8,.,8,.,8 ssh-rsa ...`

### Second problem

In the authorized key file, values like IP-addresses need quotes, otherwise I get an error. How can I handle this problem?

```
openssh:
  ...
  auth_map:
    ssh_to_host:
      source: salt://ssh/keys
      users:
        user1:
          first-key:
            options:
              - from='8.8.8.8'
              - command='uptime'
...
```

**I get the following error:**

```
 Data failed to compile:
----------
    Rendering SLS 'base:openssh.auth_map' failed: while parsing a block mapping
  in "<unicode string>", line 60, column 7:
        - options: "["from='8.8.8.8'", "co ...
          ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 60, column 19:
        - options: "["from='8.8.8.8'", "command='uptime'"]"
```

Please help me to answer my problems.
