### ISSUE TITLE
Test config before restarting service

### ISSUE THREAD

**Issue by OrangeDog** [saltstack-formulas/openssh-formula#143]
To avoid rendering a server inaccessible, should include something like this (for both .config and .config_ini)

```
/usr/sbin/sshd -t:
  cmd.run:
    - onchanges:
      - file: /etc/ssh/sshd_config
    - require_in:
      - service: ssh
```
