### ISSUE TITLE
Adding multiple keys for a user

### ISSUE THREAD

**Issue by bogdanr** [saltstack-formulas/openssh-formula#21]
I am not able to add multiple keys for the same user.
How should I do that? Right now my pillar file looks something like this:

```
openssh:
  auth:
    root:
      - name: AAAAB3NzaC1yc2EAAAADAQABAAABAQDSGAsHBf0oK5+NfnPyhTU/6/jwQ6Wp45PWzjCb5vLGM/wpmpemaMQFu58Y1mxrUBj8vQaoQ2MfN2lH7J3n/CXJ3WD9l4qwbX29lXmVxeK/wblablabla/5/sb18OiRo2pGzDifb67EOjQX7KoB26SdPqUB8mVDyhcucgu01hmHgO1rdq4pmK+uIj1gDUG4B3xpqQyLOW1nHoAUJTh+wMACg9wkGn+6yTb3Ut1SnVh20DJag203btgTx88KFLaRRUKkxObw37KsiUBV/kUmwN4aPSgvPt1NkkuDYlcMYOY6/FEw6n
        present: True
        enc: ssh-rsa
        comment: Bogdan
    www-data:
      - name: AAAAB3NzaC1yc2EAAAADAQblablablatduecy8ZD9D+tBde1S0OP7nu9F/IYDTl+mnMULzEN9mYKhGzsPCwVjGzjrlqrF4HSN/je52WNM8YxLepnjf9dKOVGtrCmYDT1S3ny0HBf0Uj7X46ntXF0B3wLVVg3tylIzbKNWFIaLuW1IpJCRl7w1FqeXQzA8deVLmHBG8okHT9HXbZvB93bf0Tvx9Axi8Jym/Krj7dLT8oeErVXr6uF+PrmtonfMsbctSrHOOflbeBu29R63wUFWFndO9Xej2SNAidunb/1dToRcTOBOaFiLh4/8S0/Mp0ZWzGFN
        present: True
        enc: ssh-rsa
        comment: Florin
    www-data:
      - name: AAAAB3NzaC1yc2EAblablablaPdEDEmCZkvsotubdcmgT/+p2KXNGjXBbvA0quoII93WCsrl1LqwBWfJOMXyWQFsF6tTi4ruLtGg9d/bSxfm/dBSg/4lePSYnEHhB+6RHL86qc/Q9f8jH5gm6rix9fCzUmTZPoYBlCpneHNIL877DrVS5LFPYWWZdupN+h98xgOtGaIhUSAWBpMSfjHcMu38TtitfYW1lxAl86fhmeDyZ0F4gy5/vOXp6BBSKsYwa3XV7G25ljMncfrEkPZlLXJyTbM9YlYiFcsHRJeOtw3J+b0B7NAssdaUIEXaRiFcYRs/duAi6h2Y6xf
        present: True
        enc: ssh-rsa
        comment: Georgian
```
The error that is produced is this:
```
    Rendering SLS 'openssh' failed, render error:
Conflicting ID 'www-data'
```
