### ISSUE TITLE
openssh.known_hosts state is broken in 2015.5.0

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/openssh-formula#34]
the mine_function needed for this state to work uses cmd.run but in 2015.5.0 there has been a change
the pillar example needs to be updated to reflect this change:

for 2015.5.0 this should be:
```
# Required for openssh.known_hosts
mine_functions:
  public_ssh_host_keys:
    mine_function: cmd.run
    cmd: cat /etc/ssh/ssh_host_*_key.pub
    python_shell: True
  public_ssh_hostname:
    mine_function: grains.get
    key: id
```
